version: "2"
run:
  go: "1.24"
linters:
  enable:
    - bidichk
    - containedctx
    - contextcheck
    - gosec
    - misspell
    - prealloc
    - reassign
    - revive
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
        use-field-name: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: releaseros
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
